#!/usr/bin/env bash
# display information about a subdomain
get_subdomain_info() {
    domain="$1"
    subdomain="$2"
    
    record_type=$(dig +short "$subdomain.$domain" | awk '{ print $1 }')
    destination=$(dig +short "$subdomain.$domain" | head -n 1)
    
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    get_subdomain_info "$domain" "$subdomain"
fi
