#!/usr/bin/env bash
# display information about a subdomain
get_subdomain_info() {
    domain="$1"
    subdomain="$2"

    result=$(dig +short "$subdomain.$domain")

    if [ -z "$result" ]; then
        echo "Error: Subdomain $subdomain not found."
        return
    fi

    record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print $4}')
    destination=$(dig +short "$subdomain.$domain")

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    get_subdomain_info "$domain" "$subdomain"
fi
