#!/usr/bin/env bash
# install nginx if not already installed
if ! command -v nginx &> /dev/null
then
   sudo apt-get -y update
   sudo apt-get -y install nginx
fi

echo "
location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}" | tee -a /etc/nginx/sites-available/default > /dev/null

service nginx reload
