#!/usr/bin/env bash

if ! command -v nginx &> /dev/null
then
    apt-get -y update
    apt-get -y install nginx
fi

echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /404 {
        internal;
        alias /var/www/html/404.html;
    }

    error_page 404 /404;

    location = /404 {
        internal;
        return 404 'Ceci n'\''est pas une page';
    }
}" | tee /etc/nginx/sites-available/default > /dev/null

echo 'Ceci n'\''est pas une page' > /var/www/html/404.html

service nginx reload
