#!/usr/bin/env bash

# Replace "myschool.tech" with your actual domain name
DOMAIN="jackita.tech"
WEB_SERVER_IP="18.204.6.30"

# Add A record to DNS
echo "$DOMAIN.    IN  A   $WEB_SERVER_IP" > /etc/bind/db.myschool

# Restart BIND (assuming BIND is your DNS server)
service bind9 restart
