#!/usr/bin/env bash
# Double the number of webservers
sudo apt-get update
sudo apt-get install -y nginx

hostname=$(hostname)

cat <<EOF | sudo tee /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By $hostname;
        root /var/www/html;
        index index.html;
    }
}
EOF

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo systemctl restart nginx
