#!/usr/bin/env bash
# record self PID in .pid file - `tee` used to invoke sudo perms, but need to redirect stdout
echo $$ | sudo tee /var/run/myscript.pid > /dev/null
trap "sudo rm /var/run/myscript.pid; echo 'I hate the kill command'; exit" SIGTERM
trap "sudo rm /var/run/myscript.pid; echo 'I hate the kill command'; exit" SIGQUIT
trap "echo 'Y U no love me?!'; exit" SIGINT
while ((1)); do
    echo 'To infinity and beyond'
    sleep 2
done
