#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
count=10
while ((count > 0)); do
    echo 'Best School'
    if [ $count -eq 2 ]; then
        echo 'Hi'
    fi
    ((count--))
done
unset count
