#!/bin/bash

# Install UFW if not already installed
sudo apt-get update
sudo apt-get install ufw -y

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (port 22)
sudo ufw allow 22

# Allow HTTPS (port 443)
sudo ufw allow 443

# Allow HTTP (port 80)
sudo ufw allow 80
#Allow incoming traffic on port 8080 and forward to port 80
sudo ufw allow 8080
sudo ufw route allow 8080 comment 'HTTP traffic to port 80'
sudo ufw route allow 8080 proto tcp from any to any port 80
# Enable UFW
sudo ufw enable

# Display UFW status
sudo ufw status
