#!/usr/bin/env bash
# local host resolves to 127.0.0.2 and facebook.com resolves to
# 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost$/127.0.0.2 localhost/' ~/hosts.new
grep -q 'facebook.com' ~/hosts.new &&
     sed -i 's/.*facebook.com$/8.8.8.8 facebook.com/' ~/hosts.new ||
