#!/usr/bin/env bash
# script to configure broken container to work with nginx at port 8080
sed -i 's/AllowOverride None/AllowOverride All/' /etc/apache2/sites-available/default
service apache2 restart
