#!/usr/bin/env bash
# script to configure broken container to work with nginx at port 8080
pkill "apache2"
sudo sed -i 's/#user www-data/nginx/g' /etc/user nginx/nginx.conf
sudo sed -i 's/\<80\>/&80/' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
